name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Boost library
      run: sudo apt-get install libboost1.70-dev
    - name: Install OpenSSL library
      run: sudo apt-get install openssl
    - name: Make project
      run: make
